config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]                                          
  as :user do
    get 'users/edit' => 'users#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise#update', :as => 'user_registration'            
  end

  resources :users
  resources :crises
  resources :surveys
  resources :survey_responses
  resources :questions
  resources :question_responses
  resources :question_groups
  resources :survey_response_filters
  resources :question_response_filters

  root 'question_responses#index'

end

app/models/question_group.rb
class QuestionGroup < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: {strict: true}
end

app/controllers/question_groups_controller.rb
class QuestionGroupsController < ApplicationController
  before_action :set_question_group, only: [:show, :edit, :update, :destroy]

  # GET /question_groups
  # GET /question_groups.json
  def index
    @question_groups = QuestionGroup.all
  end

  # GET /question_groups/1
  # GET /question_groups/1.json
  def show
  end

  # GET /question_groups/new
  def new
    @question_group = QuestionGroup.new
  end

  # GET /question_groups/1/edit
  def edit
  end

  # POST /question_groups
  # POST /question_groups.json
  def create
    @question_group = QuestionGroup.new(question_group_params)
    @question_group.user = current_user
    
    respond_to do |format|
      if @question_group.save
        format.html { redirect_to @question_group, notice: 'Question group was successfully created.' }
        format.json { render :show, status: :created, location: @question_group }
      else
        format.html { render :new }
        format.json { render json: @question_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_groups/1
  # PATCH/PUT /question_groups/1.json
  def update
    respond_to do |format|
      if @question_group.update(question_group_params)
        format.html { redirect_to @question_group, notice: 'Question group was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_group }
      else
        format.html { render :edit }
        format.json { render json: @question_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_groups/1
  # DELETE /question_groups/1.json
  def destroy
    @question_group.destroy
    respond_to do |format|
      format.html { redirect_to question_groups_url, notice: 'Question group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_group
      @question_group = QuestionGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_group_params
      params.require(:question_group).permit(:theme, :content)
    end
end

app/views/question_groups/_form.html.erb
<%= form_for(@question_group) do |f| %>
  <% if @question_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_group.errors.count, "error") %> prohibited this question_group from being saved:</h2>

      <ul>
      <% @question_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_groups/edit.html.erb
<h1>Editing Question Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_group %> |
<%= link_to 'Back', question_groups_path %>

app/views/question_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Question Groups</h1>

<table>
  <thead>
    <tr>
      <th>Theme</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_groups.each do |question_group| %>
      <tr>
        <td><%= question_group.theme %></td>
        <td><%= question_group.content %></td>
        <td><%= link_to 'Show', question_group %></td>
        <td><%= link_to 'Edit', edit_question_group_path(question_group) %></td>
        <td><%= link_to 'Destroy', question_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question group', new_question_group_path %>

app/views/question_groups/new.html.erb
<h1>New Question Group</h1>

<%= render 'form' %>

<%= link_to 'Back', question_groups_path %>

app/views/question_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Theme:</strong>
  <%= @question_group.theme %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question_group.content %>
</p>

<%= link_to 'Edit', edit_question_group_path(@question_group) %> |
<%= link_to 'Back', question_groups_path %>