config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]                                          
  as :user do
    get 'users/edit' => 'users#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise#update', :as => 'user_registration'            
  end

  resources :users
  resources :crises
  resources :surveys
  resources :survey_responses
  resources :questions
  resources :question_responses
  resources :question_groups
  resources :survey_response_filters
  resources :question_response_filters

  root 'question_responses#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  
  has_many :questions, -> { order(number: :asc) }
  accepts_nested_attributes_for :questions

  belongs_to :user
  validates :user, presence: {strict: true}
  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    @survey.user = current_user
    
    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name)
    end
end

app/views/surveys/_form.html.erb
<%= bootstrap_form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>


  <%= render 'questions_form', f: f %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_questions_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <h3>Questions</h3>

    <table class="table table-bordered">

      <thead>
        <tr>
          <th colspan="2">Question</th>
          <th>Answer</th>
        </tr>
      </thead>

      <tbody>

        <% @survey.questions.each do |question| %>
          <%= f.fields_for :questions, question do |ff| %>
            <tr>
              <td><%= ff.text_field :number, hide_label: true %></td>
              <td><%= ff.text_area :content, hide_label: true %></td>
              <td><%= ff.collection_select(:question_group_id, QuestionGroup.all, :id, :content, prompt: true) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survey.name %>

  <%= render 'form' %>

</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>