config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]                                          
  as :user do
    get 'users/edit' => 'users#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise#update', :as => 'user_registration'            
  end

  resources :users
  resources :crises
  resources :surveys
  resources :survey_responses
  resources :questions
  resources :question_responses
  resources :question_groups
  resources :survey_response_filters
  resources :question_response_filters

  root 'question_responses#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  
  has_many :questions, -> { order(number: :asc) }
  accepts_nested_attributes_for :questions

  belongs_to :user
  validates :user, presence: {strict: true}
  
end

app/controllers/question_responses_controller.rb
require 'csv'
class QuestionResponsesController < ApplicationController
  before_action :set_question_response, only: [:show, :edit, :update, :destroy]
  has_scope :question_id
  has_scope :survey_id
  has_scope :crisis_id
  has_scope :question_ids, type: :array
  # GET /question_responses
  # GET /question_responses.json
  def index
    collection = apply_scopes(QuestionResponse).includes([:survey_response, :question])
    @question_responses = collection.all
    @question_response_filter = QuestionResponseFilter.new

    @question_response_filter.assign_attributes({
      survey_id: params[:survey_id],
      crisis_id: params[:crisis_id],
      question_ids: params[:question_ids]
    })

    participant_types = collection.all.sort_by(&:participant_type).group_by(&:participant_type).keys
    labels = participant_types.dup.unshift("Answer")
    
    @answers_bar_charts = collection.all.group_by(&:question_id).map do |question_id, questions|
      answers = questions.sort_by(&:answer).group_by(&:answer).map do |answer, _questions| 
        [answer.to_i.to_words] + participant_types.map {|pt| _questions.find_all {|q| q.participant_type == pt}.size }
      end

      {
        title: Question.find(question_id).content.html_safe,
        id: question_id,
        data: answers.unshift(labels)
      }
    end



    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"question-responses.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # GET /question_responses/1
  # GET /question_responses/1.json
  def show
  end

  # GET /question_responses/new
  def new
    @question_response = QuestionResponse.new
  end

  # GET /question_responses/1/edit
  def edit
  end

  # POST /question_responses
  # POST /question_responses.json
  def create
    @question_response = QuestionResponse.new(question_response_params)
    @question_response.user = current_user

    respond_to do |format|
      if @question_response.save
        format.html { redirect_to @question_response, notice: 'Question response was successfully created.' }
        format.json { render :show, status: :created, location: @question_response }
      else
        format.html { render :new }
        format.json { render json: @question_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_responses/1
  # PATCH/PUT /question_responses/1.json
  def update
    respond_to do |format|
      if @question_response.update(question_response_params)
        format.html { redirect_to @question_response, notice: 'Question response was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_response }
      else
        format.html { render :edit }
        format.json { render json: @question_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_responses/1
  # DELETE /question_responses/1.json
  def destroy
    @question_response.destroy
    respond_to do |format|
      format.html { redirect_to question_responses_url, notice: 'Question response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_question_response
      @question_response = QuestionResponse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_response_params
      params.require(:question_response).permit(:survey_response_id, :question_id, :answer, :answer_type)
    end
end

app/views/question_responses/_answers_bar_charts.html.erb
<div class="answers-bar-charts">
  <% @answers_bar_charts.each_slice(2) do |c1, c2| %>
    <div class="row">
      <div class="col-sm-6">
        <div id="answer-bar-chart-<%= c1 && c1[:id] %>"></div>
      </div>
      <div class="col-sm-6">
        <div id="answer-bar-chart-<%= c2 && c2[:id] %>"></div>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawCharts('<%== j @answers_bar_charts.to_json %>'));

  function drawCharts(json) {
    var charts = JSON.parse(json);

    setTimeout(function() {
      var vis = google.visualization;
      
      _.forEach(charts, function(chart) {  
        var data = google.visualization.arrayToDataTable(chart.data)
        var options = {
          title : chart["title"],
          vAxis: {title: 'Participants'},
          hAxis: {title: 'Answer'},
          seriesType: 'bars',
          series: {4: {type: 'line'}}
        }
        var c = new google.visualization.ComboChart(document.getElementById('answer-bar-chart-' + chart["id"]));
        c.draw(data, options);
      });
    }, 3000);
  };

</script>

app/views/question_responses/_filter_form.html.erb
<%= bootstrap_form_for( @question_response_filter, as: '', url: question_responses_path, method: :get ) do |f| %>
  <div class="row">
    <div class="col-sm-6">
      <%= f.collection_select(:survey_id, Survey.all, :id, :name, { include_blank: true }) %>
      <%= f.collection_select(:crisis_id, Crisis.all, :id, :label, { include_blank: true }) %>
    </div>

    <div class="col-sm-6">
      <%= f.select(:question_ids, Question.all.collect {|q| [q.content, q.id]}, { include_blank: "All" }, { :multiple => true, class: 'chosen-select' }) %>
    </div>

  </div>

  <div class="row">
    <div class="col-sm-6">
      <%= f.submit "Update Filter"%>
    </div>
  </div>
<% end %>

app/views/question_responses/_form.html.erb
<%= form_for(@question_response) do |f| %>
  <% if @question_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_response.errors.count, "error") %> prohibited this question_response from being saved:</h2>

      <ul>
      <% @question_response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survey_response_id %><br>
    <%= f.text_field :survey_response_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.text_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :answer_type %><br>
    <%= f.text_field :answer_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_responses/edit.html.erb
<h1>Editing Question Response</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_response %> |
<%= link_to 'Back', question_responses_path %>

app/views/question_responses/index.csv.erb
<%- headers = ['Survey', 'Participant Type', 'Participant Id', 'Question Group', 'Question', 'Answer'] -%>
<%= CSV.generate_line headers %>
<%- @question_responses.each do |qr| -%>
<%= CSV.generate_line([
  qr.survey_response.survey.name, 
  qr.survey_response.participant_type, 
  qr.survey_response.participant_id,
  qr.question.question_group.content.gsub!(/[^0-9A-Za-z]/, ' '),
  qr.question.content.gsub!(/[^0-9A-Za-z]/, ' '),
  qr.answer
]) -%>
<%- end -%>

app/views/question_responses/index.html.erb
<h1>Listing Question Responses</h1>

<div class="row">
  <div class="col-sm-12">
    <%= link_to "Download CSV", {format:'csv', params: request.query_parameters } %>

    <a class="btn btn-default pull-right" role="button" data-toggle="collapse" href="#filters" aria-expanded="false" aria-controls="collapseExample">
      Filters
    </a>

  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="collapse" id="filters">
      <br>
      <div class="well">
        <%= render 'filter_form' %>
      </div>
    </div>
  </div>
</div>


<% if @answers_bar_charts %>
  <%= render 'answers_bar_charts' %>
<% end %>


<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th>Survey</th>
          <th>Participant</th>
          <th>Crisis</th>
          <th>Response Date</th>
          <th>Question</th>
          <th>Answer</th>
        </tr>
      </thead>

      <tbody>
        <% @question_responses.each do |question_response| %>
          <tr>
            <td><%= question_response.survey_response.survey.name %></td>
            <td><%= question_response.survey_response.participant_type %></td>
            <td><%= question_response.survey_response.crisis.label %></td>
            <td><%= question_response.survey_response.date %></td>
            <td><%= question_response.question.content %></td>
            <td><%= question_response.answer %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

  </div>
</div>

app/views/question_responses/new.html.erb
<h1>New Question Response</h1>

<%= render 'form' %>

<%= link_to 'Back', question_responses_path %>

app/views/question_responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Survey response:</strong>
  <%= @question_response.survey_response %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question_response.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question_response.answer %>
</p>

<p>
  <strong>Type:</strong>
  <%= @question_response.answer_type %>
</p>

<%= link_to 'Edit', edit_question_response_path(@question_response) %> |
<%= link_to 'Back', question_responses_path %>